### ISSUE TITLE
Superimpose position histograms

### ISSUE THREAD

**Issue by brembs** [brembslab/DTSevaluations#14]
Currently, position histograms are ignorant of which quadrants are punished and which not. The histograms should show if the flies avoided heated quadrants or not.

**Comment by brembs** [comment]
Actually, the same would need to be done for the torque histograms in torque learning...

**Comment by Eanders1** [comment]
My current version of this DOES change the orientation of the graphs so that the punished side is always to the left, problem is that the aesthetics somewhat differ between reverse and non-reversed.  I did this by simply reversing the x axis, and within this reverse-command I added the appropriate axis, breaks and labels. I wrote an if else where it either reverses or not reverses the axis. This works but the aesthetics of these two generate somewhat different graphs. This is only true for the single fly evaluation and not the grouped one.

**Comment by Eanders1** [comment]
The problem is that minor breaks on the x axis are not calculated correctly, it seems to be a known issue.

**Comment by Eanders1** [comment]
[left example.pdf](https://github.com/brembslab/DTSevaluations/files/3635258/left.example.pdf)
[right example.pdf](https://github.com/brembslab/DTSevaluations/files/3635259/right.example.pdf)

**Comment by brembs** [comment]
done!
